apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    istio: in-cluster-current-istio-ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - grafana.qrunio.dev
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - grafana.qrunio.dev
      tls:
        mode: SIMPLE
        credentialName: grafana-cert
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grafana
  namespace: monitoring
spec:
  hosts:
    - "*"
  gateways:
    - grafana
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: istio-system
spec:
  secretName: grafana-cert
  commonName: grafana.qrunio.dev
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.qrunio.dev