apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istiod
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - list:
        elements:
          - targetRevision: 1.21.5
            destination:
              name: in-cluster
              revision: current
          - targetRevision: 1.21.5
            destination:
              name: in-cluster
              revision: canary
  template:
    metadata:
      name: '{{.destination.name}}-{{.destination.revision}}-istiod'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: istiod
        targetRevision: '{{.targetRevision}}'
        helm:
          valuesObject:
            revision: '{{.destination.revision}}'
      destination:
        name: '{{.destination.name}}'
        namespace: istio-system
      ignoreDifferences:
        - group: "admissionregistration.k8s.io"
          kind: "ValidatingWebhookConfiguration"
          jsonPointers:
            - /webhooks/0/failurePolicy # this changed later by istiod
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
